-- szh-import.lua — passe A de l'import docx -> md (D27/D28).
-- Heuristiques FONDÉES sur l'analyse AST des 6 articles réels de la revue 2026-01 :
--   1. suppression des titres vides (« Piricò » : header vide au milieu de la biblio) ;
--   2. titres déduits des paragraphes tout-gras courts (« Chanier » : zéro style Word) ;
--   3. listes à puces manuelles regroupées en vraies listes (filet de sécurité) ;
--   4. figures : légende détectée dans le paragraphe voisin (avant OU après), numéro
--      manuel retiré (numérotation auto par CSS, D31), alt-texts IA purgés ;
--   5. tableaux : légende voisine -> caption du tableau ;
--   6. détection de la liste de références par CONTENU + POSITION (pas par titre),
--      entrées multi-paragraphes regroupées (« Dentz ») -> écrites dans SZH_REFS
--      pour AnyStyle, et retirées du document (citeproc les régénérera).
-- Environnement : SZH_STATS (json de rapport), SZH_REFS (sortie texte des références).

local stats = {
  titres_reels = 0, titres_vides_supprimes = 0, titres_deduits = {},
  listes_reconstruites = 0, notes = 0, images = 0,
  figures_legendees = 0, figures_sans_legende = 0, alt_ia_purges = 0,
  numeros_figures_retires = {}, tableaux = 0, tableaux_legendes = 0,
  refs = { n = 0, titre = '', entrees = {} },
  avertissements = {},
}

local utils = pandoc.utils

-- espaces spéciaux (insécables, fines) -> espace simple ; tirets spéciaux -> '-'.
-- Les Word français en sont truffés : sans cela, ni trim ni les motifs ne matchent.
local function assainir(t)
  t = t:gsub('\194\160', ' '):gsub('\226\128\175', ' '):gsub('\226\128\137', ' ')
  t = t:gsub('\226\128\147', '-'):gsub('\226\128\148', '-'):gsub('\226\128\145', '-')
  return t
end

local function s(x) return assainir(utils.stringify(x)) end

local function trim(t) return (t:gsub('^%s+', ''):gsub('%s+$', '')) end

-- ---------- petits prédicats ----------

local function est_vide(bloc)
  if trim(s(bloc)) ~= '' then return false end
  -- ⚠ stringify(Image) = alt-text : une image sans alt rendrait le bloc « vide ».
  local contient_objet = false
  pandoc.walk_block(bloc, {
    Image = function() contient_objet = true end,
    Note = function() contient_objet = true end,
  })
  return not contient_objet
end

local function tout_gras(inls)
  local reel = 0
  for _, i in ipairs(inls) do
    if i.t ~= 'Space' and i.t ~= 'SoftBreak' then
      if i.t ~= 'Strong' then return false end
      reel = reel + 1
    end
  end
  return reel > 0
end

local function nb_mots(txt)
  local n = 0
  for _ in txt:gmatch('%S+') do n = n + 1 end
  return n
end

-- Légendes : Figure 1 : … / Fig. 2 — … / Abbildung 3: … / Tableau 1. …
local MOTS_FIGURE = '^[Ff]igure%s+%d+[a-z]?%s*[:%.%-–—]?%s*'
local MOTS_FIG2   = '^[FfAa]bb?%.%s*%d+[a-z]?%s*[:%.%-–—]?%s*'
local MOTS_ABB    = '^[Aa]bbildung%s+%d+[a-z]?%s*[:%.%-–—]?%s*'
local MOTS_ILLU   = '^[Ii]llustration%s+%d+[a-z]?%s*[:%.%-–—]?%s*'
local MOTS_TABLE  = '^[Tt]ab[l]?[e]?[a]?[u]?l?l?e?%s+%d+[a-z]?%s*[:%.%-–—]?%s*'  -- Table/Tableau/Tabelle

local function legende_figure(txt)
  for _, motif in ipairs({ MOTS_FIGURE, MOTS_FIG2, MOTS_ABB, MOTS_ILLU }) do
    if txt:match(motif) then return trim(txt:gsub(motif, '', 1)), txt:match('%d+') end
  end
  return nil
end

local function legende_tableau(txt)
  if txt:match('^[Tt]ableau%s+%d') or txt:match('^[Tt]abelle%s+%d') or txt:match('^[Tt]able%s+%d') then
    local reste = txt:gsub('^%a+%s+%d+[a-z]?%s*[:%.%-–—]?%s*', '', 1)
    return trim(reste), txt:match('%d+')
  end
  return nil
end

-- Alt-texts pollués par Word (« Le contenu généré par l'IA peut être incorrect »)
local function alt_pollue(txt)
  local b = txt:lower()
  return b:find('généré par l', 1, true) or b:find('generated by ai', 1, true)
      or b:find('ki%-generierte') or b:find('kann fehlerhaft', 1, true)
      or b:find('une image contenant', 1, true) or b:find('ein bild, das', 1, true)
      or b:find('a picture containing', 1, true)
end

-- Une ligne « ressemble à une référence » ?
local function est_ref(txt)
  if #txt < 25 then return false end
  if txt:match('^https?://') then return true end
  local annee = txt:match('[%(%,%s][12][09]%d%d[a-z]?[%)%.,;%s]')
  local special = txt:find('sous presse', 1, true) or txt:find('en préparation', 1, true)
      or txt:find('in press', 1, true) or txt:find('im Druck', 1, true)
  if not (annee or special) then return false end
  -- au moins un motif « Nom, X. » ou une majuscule suivie d'un point (initiale) ou un éditeur
  return txt:match('%u%.') ~= nil or txt:match('^%u[%a\'’%-]+,') ~= nil or txt:match('https?://') ~= nil
end

-- ---------- passe principale ----------

function Pandoc(doc)
  local blocs = doc.blocks
  local sortie = pandoc.List()

  -- 1) purge des blocs vides (headers ET paragraphes)
  for _, b in ipairs(blocs) do
    if (b.t == 'Header' or b.t == 'Para' or b.t == 'Plain') and est_vide(b) then
      if b.t == 'Header' then stats.titres_vides_supprimes = stats.titres_vides_supprimes + 1 end
    else
      sortie:insert(b)
    end
  end
  blocs = sortie

  -- 2) titre du document + titres déduits (paragraphes tout-gras courts)
  local a_titre_meta = doc.meta.title ~= nil and trim(s(doc.meta.title)) ~= ''
  sortie = pandoc.List()
  for idx, b in ipairs(blocs) do
    local remplace = nil
    if b.t == 'Header' then stats.titres_reels = stats.titres_reels + 1 end
    if b.t == 'Para' and tout_gras(b.content) then
      local txt = trim(s(b))
      if #txt >= 2 and #txt <= 90 and nb_mots(txt) <= 15
         and not txt:match('[%.;:]$') and not txt:match('^[•▪◦%-–]') then
        -- déballer gras/souligné/span : un titre n'a pas besoin de ces couches
        local function deballer(liste)
          local out = pandoc.List()
          for _, i in ipairs(liste) do
            if i.t == 'Strong' or i.t == 'Underline' or i.t == 'Span' then
              out:extend(deballer(i.content))
            else
              out:insert(i)
            end
          end
          return out
        end
        local inls = deballer(b.content)
        if idx == 1 and not a_titre_meta then
          doc.meta.title = pandoc.MetaInlines(inls)
          a_titre_meta = true
          remplace = 'supprime'
          stats.titres_deduits[#stats.titres_deduits + 1] = txt .. ' [titre du document]'
        else
          remplace = pandoc.Header(2, inls)
          stats.titres_deduits[#stats.titres_deduits + 1] = txt
        end
      end
    end
    if remplace == 'supprime' then -- rien
    elseif remplace then sortie:insert(remplace)
    else sortie:insert(b) end
  end
  blocs = sortie

  -- 3) listes à puces manuelles (runs d'au moins 2 paragraphes commençant par une puce)
  local function marqueur_puce(b)
    if b.t ~= 'Para' then return nil end
    local txt = s(b)
    return txt:match('^[•▪◦]%s+') or txt:match('^[%-–]%s+')
  end
  sortie = pandoc.List()
  local i = 1
  while i <= #blocs do
    if marqueur_puce(blocs[i]) and i < #blocs and marqueur_puce(blocs[i + 1]) then
      local items = pandoc.List()
      while i <= #blocs and marqueur_puce(blocs[i]) do
        local inls = pandoc.List(blocs[i].content)
        -- retirer le marqueur au début du premier Str
        if inls[1] and inls[1].t == 'Str' then
          local nettoye = inls[1].text:gsub('^[•▪◦%-–]+', '')
          if nettoye == '' then inls:remove(1); if inls[1] and inls[1].t == 'Space' then inls:remove(1) end
          else inls[1] = pandoc.Str(nettoye) end
        end
        items:insert({ pandoc.Plain(inls) })
        i = i + 1
      end
      sortie:insert(pandoc.BulletList(items))
      stats.listes_reconstruites = stats.listes_reconstruites + 1
    else
      sortie:insert(blocs[i])
      i = i + 1
    end
  end
  blocs = sortie

  -- 4) figures : image seule dans un paragraphe + légende voisine
  -- Pré-passe : normaliser les paragraphes d'images réels (fondé sur « Leclerc ») :
  --   [Image, Str-déchet] -> [Image] ;  [Image, Space, Image] -> deux paragraphes.
  sortie = pandoc.List()
  for _, b in ipairs(blocs) do
    if b.t == 'Para' then
      local images, residu = pandoc.List(), ''
      for _, x in ipairs(b.content) do
        if x.t == 'Image' then images:insert(x)
        elseif x.t ~= 'Space' and x.t ~= 'SoftBreak' then residu = residu .. s(x) end
      end
      if #images >= 1 and #trim(residu) <= 2 then
        for _, img in ipairs(images) do sortie:insert(pandoc.Para({ img })) end
      else
        sortie:insert(b)
      end
    else
      sortie:insert(b)
    end
  end
  blocs = sortie

  local function para_image(b)
    if b.t ~= 'Para' then return nil end
    local img = nil
    for _, x in ipairs(b.content) do
      if x.t == 'Image' then
        if img then return nil end -- plusieurs images : ne pas toucher
        img = x
      elseif x.t ~= 'Space' and x.t ~= 'SoftBreak' then
        return nil
      end
    end
    return img
  end

  local consommes = {}   -- indices de légendes absorbées
  sortie = pandoc.List()
  for idx, b in ipairs(blocs) do
    if consommes[idx] then goto continue end
    local img = para_image(b)
    if img then
      stats.images = stats.images + 1
      -- purge alt IA
      if alt_pollue(s(img.caption)) then
        img.caption = pandoc.Inlines({})
        stats.alt_ia_purges = stats.alt_ia_purges + 1
      end
      -- légende avant ou après ? (avant d'abord : style dominant observé)
      local cap, num, capidx = nil, nil, nil
      for _, j in ipairs({ idx - 1, idx + 1 }) do
        local v = blocs[j]
        if v and v.t == 'Para' and not consommes[j] and not para_image(v) then
          local c, n = legende_figure(s(v))
          if c and c ~= '' then cap, num, capidx = c, n, j; break end
        end
      end
      if cap then
        consommes[capidx] = true
        if num then stats.numeros_figures_retires[#stats.numeros_figures_retires + 1] = num end
        local capinls = pandoc.Inlines({ pandoc.Str(cap) })
        if capidx == idx - 1 then
          -- la légende précédait : retirer le bloc déjà émis
          sortie:remove(#sortie)
        end
        img.caption = capinls
        sortie:insert(pandoc.Figure(pandoc.Blocks({ pandoc.Plain({ img }) }),
                                    { long = pandoc.Blocks({ pandoc.Plain(capinls) }) }))
        stats.figures_legendees = stats.figures_legendees + 1
      else
        stats.figures_sans_legende = stats.figures_sans_legende + 1
        sortie:insert(b)
      end
    elseif b.t == 'Table' then
      stats.tableaux = stats.tableaux + 1
      -- légende voisine (avant ou après)
      local cap, num, capidx = nil, nil, nil
      for _, j in ipairs({ idx - 1, idx + 1 }) do
        local v = blocs[j]
        if v and v.t == 'Para' and not consommes[j] then
          local c, n = legende_tableau(s(v))
          if c and c ~= '' then cap, num, capidx = c, n, j; break end
        end
      end
      if cap then
        consommes[capidx] = true
        if capidx == idx - 1 then sortie:remove(#sortie) end
        b.caption = { long = pandoc.Blocks({ pandoc.Plain({ pandoc.Str(cap) }) }) }
        stats.tableaux_legendes = stats.tableaux_legendes + 1
      end
      sortie:insert(b)
    else
      sortie:insert(b)
    end
    ::continue::
  end
  blocs = sortie

  -- 5) détection de la liste de références (contenu + position, D28)
  local dernier_ref = nil
  for idx = #blocs, math.max(1, #blocs - 80), -1 do
    local b = blocs[idx]
    if b.t == 'Para' and est_ref(s(b)) then dernier_ref = idx; break end
  end
  if dernier_ref and dernier_ref >= math.floor(#blocs * 0.5) then
    -- remontée : Para ref/continuation absorbés ; Table/Figure SAUTÉS (bio insérée
    -- au milieu de la biblio, « Piricò ») ; premier Header rencontré = titre absorbé.
    local a_retirer = {}
    a_retirer[dernier_ref] = true
    local suspens = 0
    local k = dernier_ref - 1
    while k >= 1 do
      local b = blocs[k]
      if b.t == 'Para' then
        local txt = trim(s(b))
        if est_ref(txt) then
          a_retirer[k] = true; suspens = 0
        elseif #txt > 0 and #txt < 280 and suspens < 2 then
          a_retirer[k] = true; suspens = suspens + 1   -- continuation (« Dentz »)
        else
          break
        end
      elseif b.t == 'Header' then
        stats.refs.titre = trim(s(b))
        a_retirer[k] = true
        break
      elseif b.t == 'Table' or b.t == 'Figure' then
        -- élément intercalé (bio, encadré) : on le saute sans l'absorber
      else
        break
      end
      k = k - 1
    end
    -- redescente : références égarées APRÈS un tableau/bio en fin de document
    local j = dernier_ref + 1
    while j <= #blocs do
      local b = blocs[j]
      if b.t == 'Para' and est_ref(trim(s(b))) then
        a_retirer[j] = true
      elseif b.t == 'Table' or b.t == 'Figure' then
        -- sauter
      else
        break
      end
      j = j + 1
    end
    -- regrouper les entrées dans l'ordre (continuations collées à l'entrée précédente)
    local entrees = {}
    for idx = 1, #blocs do
      if a_retirer[idx] and blocs[idx].t == 'Para' then
        local txt = trim(s(blocs[idx]))
        if txt ~= '' then
          -- nouvelle entrée seulement si elle COMMENCE comme une référence
          -- (majuscule) ; minuscule ou URL = suite de l'entrée précédente (« Dentz »)
          if est_ref(txt) and not txt:match('^https?://') and txt:match('^[%u«"]') then
            entrees[#entrees + 1] = txt
          elseif #entrees > 0 then
            entrees[#entrees] = entrees[#entrees] .. ' ' .. txt
          else
            entrees[#entrees + 1] = txt
          end
        end
      end
    end
    if #entrees >= 3 then
      stats.refs.n = #entrees
      stats.refs.entrees = entrees
      local chemin = os.getenv('SZH_REFS')
      if chemin then
        local f = io.open(chemin, 'w')
        if f then
          for _, e in ipairs(entrees) do f:write(e, '\n') end
          f:close()
        end
      end
      local garde = pandoc.List()
      for idx, b in ipairs(blocs) do
        if not a_retirer[idx] then garde:insert(b) end
      end
      blocs = garde
    else
      stats.avertissements[#stats.avertissements + 1] = 'liste-references-trop-courte'
    end
  else
    stats.avertissements[#stats.avertissements + 1] = 'pas-de-liste-references-detectee'
  end

  -- 6) compter les notes de bas de page (converties nativement par pandoc)
  doc.blocks = blocs
  doc:walk({ Note = function() stats.notes = stats.notes + 1 end })

  -- 7) stats -> JSON pour le rapport
  local chemin = os.getenv('SZH_STATS')
  if chemin then
    local f = io.open(chemin, 'w')
    if f then
      f:write(pandoc.json.encode(stats))
      f:close()
    end
  end

  return doc
end
