"""Lignes JSON au format exact de chaque moissonneur, avec des valeurs fictives.

Une entrée par site d'émission : (ligne, types d'événements pronto-moisson/1 attendus).
"""

RECHERCHE = [
    ({'type': 'progression', 'etape': 'moisson', 'source': 'skbf', 'statut': 'budget', 'requetes': 30},
     ['etape']),
    ({'type': 'progression', 'etape': 'moisson', 'source': 'skbf', 'statut': 'echec', 'raison': '403'},
     []),
    ({'type': 'progression', 'etape': 'moisson', 'source': 'hfh', 'statut': 'echec',
      'raison': 'URLError: délai dépassé'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'moisson', 'source': 'hfh', 'statut': 'ok', 'nouveaux': 2, 'requetes': 12},
     ['etape']),
    ({'type': 'progression', 'etape': 'moisson', 'source': 'hfh', 'statut': 'arret', 'requetes': 12},
     ['etape']),
    ({'type': 'progression', 'etape': 'propositions', 'statut': 'ok', 'ecrites': 3, 'lot': '2026-11-01-1.jsonl'},
     ['etape']),
    ({'type': 'progression', 'etape': 'propositions', 'statut': 'echec', 'raison': 'OSError: disque plein'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'purge', 'statut': 'ok', 'lots': 1, 'decisions': 0, 'echecs': 0},
     ['etape']),
    ({'type': 'progression', 'etape': 'purge', 'statut': 'echec', 'raison': 'OSError: lecture seule'},
     ['avertissement']),
    ({'type': 'resume', 'moissonneur': 'recherche', 'contrat': 1, 'derniere_moisson': '2026-11-01T06:00:00Z',
      'duree_s': 40.2, 'requetes': 12, 'propositions_ecrites': 3, 'lot': '2026-11-01-1.jsonl',
      'sources_en_echec': [], 'interrompu': None, 'erreur': '', 'purge': {'lots': ['2026-04-01-1.jsonl'],
                                                                          'decisions': []},
      'nouveaux': {'hfh': 2}, 'retenues': 2, 'a_relire': 1, 'existants': 0, 'decidees': 0,
      'etapes_en_echec': []},
     ['lot']),
    ({'type': 'resume', 'moissonneur': 'recherche', 'contrat': 1, 'derniere_moisson': '2026-11-01T06:00:00Z',
      'duree_s': 0, 'requetes': 0, 'propositions_ecrites': 0, 'lot': '', 'sources_en_echec': [],
      'interrompu': 'configuration', 'erreur': 'ConfigurationInvalide: bibliothèque absente',
      'purge': {'lots': [], 'decisions': []}},
     ['avertissement']),
    # Lignes de la recherche embarquée (recherche/tout.py) : attente longue, 403 annoncé par la source elle-même.
    ({'type': 'attente', 'source': 'site:phbern', 'hote': 'www.phbern.example', 'secondes': 120, 'motif': '429'},
     ['attente']),
    ({'type': 'progression', 'etape': 'moisson', 'source': 'site:phsg', 'statut': 'echec', 'raison': '403'},
     []),
    ({'type': 'avertissement', 'source': 'site:phsg', 'code': '403',
      'message': "PH St. Gallen a refusé l’accès (403)"},
     ['avertissement']),
    ({'type': 'resume', 'moissonneur': 'recherche', 'contrat': 1, 'requetes': 14, 'propositions_ecrites': 0,
      'lot': '', 'sources_en_echec': [{'source': 'site:phsg', 'raison': '403'}], 'interrompu': None,
      'erreur': '', 'purge': {'lots': [], 'decisions': []},
      'sources_desactivees': [{'source': 'site:phlu', 'depuis': '2026-10-04'}]},
     []),
]

PARLEMENT = [
    ({'type': 'progression', 'etape': 'restauration', 'statut': 'ok',
      'detail': 'base restaurée depuis sauvegarde-2026-10-01.sqlite.gz'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'import-affaires', 'affaires': 120}, ['etape']),
    ({'type': 'progression', 'etape': 'import-documents', 'corps': 'GE', 'candidates': 4}, ['etape']),
    ({'type': 'progression', 'etape': 'import', 'statut': 'ok', 'requetes': 0, 'fichiers': 3, 'corps': 2},
     ['etape']),
    ({'type': 'progression', 'etape': 'import', 'statut': 'echec', 'raison': 'HTTPError: 404'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'mensuelle', 'statut': 'ok', 'requetes': 412, 'recherche': 12, 'textes': 30},
     ['etape']),
    ({'type': 'progression', 'etape': 'mensuelle', 'statut': 'plafond', 'requetes': 800, 'recherche': 0,
      'textes': 0},
     ['etape']),
    ({'type': 'progression', 'etape': 'mensuelle', 'statut': 'echec', 'raison': 'KeyError: x'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'moisson', 'corps': 'BE', 'statut': 'budget'}, ['etape']),
    ({'type': 'progression', 'etape': 'moisson', 'corps': 'BE', 'statut': 'echec', 'raison': '403'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'moisson', 'corps': 'GE', 'statut': 'ok', 'raison': '', 'nouvelles': 3,
      'modifiees': 1, 'requetes': 14},
     ['etape']),
    ({'type': 'progression', 'etape': 'moisson', 'corps': 'VD', 'statut': 'echec', 'raison': 'HTTPError: 500',
      'nouvelles': 0, 'modifiees': 0, 'requetes': 15},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'moisson', 'statut': 'echec', 'raison': 'ValueError: page'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'criblage', 'statut': 'ok', 'requetes': 40, 'termes': 18,
      'termes_en_echec': 0},
     ['etape']),
    ({'type': 'progression', 'etape': 'criblage', 'statut': 'budget'}, ['etape']),
    ({'type': 'progression', 'etape': 'criblage', 'statut': 'echec', 'raison': '403'}, ['avertissement']),
    ({'type': 'progression', 'etape': 'titres', 'statut': 'ok', 'requetes': 40, 'candidats_par_titre': 6},
     ['etape']),
    ({'type': 'progression', 'etape': 'textes', 'statut': 'ok', 'requetes': 52, 'textes': 12, 'echecs': 0},
     ['etape']),
    ({'type': 'progression', 'etape': 'textes', 'statut': 'budget'}, ['etape']),
    ({'type': 'progression', 'etape': 'classement', 'statut': 'ok', 'requetes': 52, 'retenu': 5, 'a_relire': 9,
      'ecarte': 300},
     ['etape']),
    ({'type': 'progression', 'etape': 'liste', 'statut': 'ok', 'requetes': 52, 'chemin': 'sortie/liste.md',
      'lignes': 14},
     ['etape']),
    ({'type': 'progression', 'etape': 'propositions', 'statut': 'ok', 'requetes': 52, 'ecrites': 14,
      'ecartees': 2, 'lot': '2026-11-01-1.jsonl', 'controle_noms': {'defauts': 0, 'lignes_avec_doute': 0}},
     ['etape']),
    ({'type': 'progression', 'etape': 'controle-noms', 'statut': 'echec',
      'raison': '1 ligne(s) retenue(s) hors lot : nom de personne non coupé'},
     ['avertissement']),
    ({'type': 'progression', 'etape': 'finesse', 'statut': 'ok', 'requetes': 52, 'termes': 18}, ['etape']),
    ({'type': 'progression', 'etape': 'purge', 'statut': 'ok', 'requetes': 52, 'lots': 1, 'decisions': 2,
      'echecs': 0},
     ['etape']),
    ({'type': 'progression', 'etape': 'sauvegarde', 'statut': 'ok', 'requetes': 52,
      'chemin': 'sauvegardes/base-2026-11-01.sqlite.gz'},
     ['etape']),
    ({'type': 'resume', 'moissonneur': 'parlement', 'contrat': 1, 'nouvelles_affaires': 3, 'affaires_modifiees': 1,
      'retenues': 5, 'a_relire': 9, 'retenues_classement': 5, 'a_relire_classement': 9, 'ecartees': 300,
      'propositions_ecrites': 14, 'lot': '/x/sortie/propositions/2026-11-01-1.jsonl', 'hors_lot_filtre': 0,
      'hors_lot_arriere': 0, 'controle_noms': {'defauts': 0, 'lignes_avec_doute': 0},
      'purge': {'lots': ['2026-04-01-1.jsonl'], 'decisions': ['a.json', 'b.json']},
      'requetes': 52, 'requetes_depuis_cache': 0,
      'sources_en_echec': [{'source': 'VD', 'raison': 'HTTPError: 500'}], 'etapes_en_echec': [],
      'interrompu': None, 'sauvegarde': 'b.gz', 'liste': 'l.md', 'base': 'base.sqlite', 'duree_s': 120.0,
      'derniere_moisson': '2026-11-01T06:00:00Z'},
     ['lot']),
    ({'type': 'resume', 'moissonneur': 'parlement', 'contrat': 1, 'interrompu': 'configuration',
      'erreur': 'base inutilisable', 'requetes': 0, 'sources_en_echec': [], 'etapes_en_echec': []},
     ['avertissement']),
    # Sous-commandes de harvest.py (hors de `tout`) : le compteur « requêtes x/800 » et la passe seule.
    ({'type': 'compteur', 'mois': '2026-11', 'requetes': 412, 'budget': 800, 'restant': 388, 'dernieres': []},
     ['etape']),
    ({'type': 'mensuelle', 'statut': 'ok', 'requetes': 36, 'corps': {}, 'sans_repere': [], 'sans_date': 0,
      'recherche': 12, 'textes': 5},
     ['etape']),
    ({'type': 'import', 'fichiers': 3, 'octets': 1000, 'corps': {}}, ['etape']),
]

# Ligne `estimer` réelle des deux moissonneurs : `requetes_prevues`, pas `requetes`.
ESTIMATION_REELLE = {'type': 'estimation', 'moissonneur': 'parlement', 'contrat': 1, 'pret': True, 'etapes': [],
                     'requetes_prevues': 40, 'budget': 800, 'depasse_le_budget': False, 'delai_s': 2.0,
                     'duree_estimee_s': 80, 'avertissements': ['base absente : reprise depuis la sauvegarde x']}
